version: 0.1.1
branches:
  only:
    - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_tags: true
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
build:
  project: Suby
  publish_nuget: true
  include_nuget_references: true
  verbosity: normal
skip_commits:
  files:
    - '**/*.md'
deploy:
  - provider: NuGet
    on:
      branch: master
    api_key:
      secure: bFMIvInvgG1fGl+fI1Za1V1LvQdhWuEBTFGTvr0iluFl03x+7mG7BwUth/nwc3NI
    artifact: /.*\.nupkg/
