image: Visual Studio 2017
configuration: Release

version: 0.0.{build}
environment:
  version: 0.0.{build}

#skip_branch_with_pr: true
#skip_tags: true
#skip_commits:
#  files:
#    - '**/*.md'
nuget:
  #disable_publish_on_pr: true
  project_feed: true
before_build:
  - nuget restore
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
#after_build:
#  - nuget pack
#init:
#  - git config --global core.autocrlf input
#test: off
#artifacts:
#  - path: .\.nupkgs\*.nupkg
deploy:
- provider: NuGet
#  server: https://api.nuget.org/v3/
  on:
    branch: master  
  api_key:
    secure: bFMIvInvgG1fGl+fI1Za1V1LvQdhWuEBTFGTvr0iluFl03x+7mG7BwUth/nwc3NI
  artifact: /.*\.nupkg/
  